kill:
  self: '&aYou have killed yourself.'
  other: '&aYou have killed &b{target}'
  target: '&aYou have been killed by &b{player}'
killall:
  format: '&aYou killed &e{total} &aentities of type &b{type}'
clearinv:
  self: '&aYou have cleared your inventory.'
  other: '&aYou have cleared the inventory of &b{target}'
  target: '&aYour inventory has been cleared by &b{player}'
top:
  self: '&aYou have teleported yourself to the highest block at your location.'
  other: '&aYou have teleported &b{target} &ato the highest block at their location'
  target: '&aYou have been teleported to the highest block at your location by &b{player}'
spawnmob:
  settings: 
    limit: 10
  messages:
    single: '&aYou have spawned a(n) &b{entity}'
    multiple: '&aYou have spawned &b{amount} &aof &b{entity}'
weather:
  format: '&aYou have set the weather to &b{type} &afor &b{duration} &ain &b{world}'
time:
  current: '&aThe current time in &b{world} &ais &b{time}'
  displayformat: '12h'
  set: '&aYou set the time in &b{world} &ato &b{time}'
spawner:
  set: '&aYou set the spawner to now spawn &b{entity}'