main: com.starmediadev.plugins.staressentials.StarEssentials
version: ${project.version}
name: ${project.name}
api-version: 1.18
description: ${project.description}
depend: [StarMCUtils]
commands: 
    broadcast:
      aliases: [bc]
    feed:
    fly:
    heal: 
    kill:
    killall:
    clearinv:
    god:
    inventorysee:
        aliases: [invsee]
    enderchest:
        aliases: [echest]
    workbench:
        aliases: [wb]
    trash:
    top:
    gamemode:
        aliases: [gm]
    gmc:
    gms:
    gmsp:
    gma: