main: com.starmediadev.plugins.staressentials.StarEssentials
version: ${project.version}
name: ${project.name}
api-version: 1.18
description: ${project.description}
depend: [StarMCUtils]
commands: 
    kill:
    killall:
    clearinv:
    inventorysee:
        aliases: [invsee]
    enderchest:
        aliases: [echest]
    workbench:
        aliases: [wb]
    trash:
    top:
    gamemode:
        aliases: [gm]
    gmc:
    gms:
    gmsp:
    gma:
    spawnmob:
        aliases: [spawnentity]
    weather:
    time:
    spawner:
    signedit:
    sethome:
    delhome:
    home:
    listhomes:
    renamehome: