main: com.starmediadev.plugins.staressentials.StarEssentials
version: ${project.version}
name: ${project.name}
api-version: 1.18
description: ${project.description}
commands: 
    broadcast:
      aliases: [bc]