main: com.starmediadev.plugins.staressentials.StarEssentials
version: ${project.version}
name: ${project.name}
api-version: 1.18
description: ${project.description}
depend: [StarMCUtils]
commands: 
    broadcast:
      aliases: [bc]
    feed:
    fly:
    heal: 